#!/bin/bash

#This script updates security settings for linux scripts

#Declare Variables
path="/"
user=$SUDO_USER

#Display Msg
echo "Leninux, Cyber Centurion Security Protocols Updater"

#Check that the script is being run as sudo

currentUser=$(whoami)

if [[ " $currentUser " != *"root"* ]];
then
	#Not root
	echo "The script must be run as root, use sudo!"
	exit
fi


#Check forensic Questions Asked
echo "Are you sure you won't to update security setting, MAKE SURE YOU COMPLETE FORENSIC QUESTIONS FIRST"
read -p "Continue (Y/N): " confirmation

if [[ " $confirmation " != *"Y"* ]];
then
	#Not confirmed
	echo "Operation Cancelled"
	exit
fi

echo "Do you want to enable SSH server"
read -p "Enable SSH (Y/N): " sshenabled

#Execute Script


#Start system update 

gnome-terminal -- sh -c "sudo apt upgrade && sudo apt update && echo 'System Updated'; bash"


#Download Files from GitHub 
path="/home/"$user"/Desktop/security"
git clone https://github.com/callumw123/Leninux $path

#copy files over

#Update Authentication Settings

cp $path/CommonPassword /etc/pam.d/common-password #Common Password
cp $path/CommonAuth /etc/pam.d/common-auth #Common Auth
cp $path/LoginDefs /etc/login.defs #Login Defs

echo "Security Settings Updated"

#Setup SSH

if [[ " $sshenabled " == *"Y"* ]];
then
	#Update SSH
	apt install openssh-server
	cp $path/sshconfig /etc/ssh/sshd_config #ssh settings
	service ssh restart
	echo "SSH updated and secured"
fi

#Disable Guest and usernames on login page

apt install lightdm
cp $path/Guest /etc/lightdm/lightdm.conf #Guest
echo "Guest Disabled"

#Disable Root Login

passwd -l root	
	
echo "Root Login Disabled"

#Enable Firewall

apt install ufw && apt install gufw
ufw enable

#Setup Firewall Settings

sysctl -n net.ipv4.tcp_syncookies #Enable sys Cookie Protection
echo net.ipv6.conf.all.disable_ipv6 | sudo tee -a /etc/sysctl.conf #Disable IPv6
sudo echo 0 | sudo tee -a /proc/sys/net/ipv4/ip_forward #Disable IP Forwarding

echo "Firewall Enabled"

#Install and update antivirus (clamav)

sudo apt install clamav 
echo 'Clamav Installed'

#Setup Audit Policy
apt-get install auditd
auditctl -e 1
	
echo "Audit Policy Enabled"


echo "All Security Settings Updated"
